# Generated by Django 5.0.6 on 2024-06-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaje', '0002_alter_registro_fin_alter_registro_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fin',
            field=models.DateTimeField(null=True),
        ),
    ]
