# Generated by Django 5.0.6 on 2024-06-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichaje', '0003_alter_registro_fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='inicio',
            new_name='inici',
        ),
    ]
