# Generated by Django 5.0.6 on 2024-06-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichaje', '0004_rename_inicio_registro_inici'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='inici',
            new_name='inicio',
        ),
    ]
