# Generated by Django 5.0.4 on 2024-05-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cif_nif', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('foto_perfil', models.BinaryField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=models.CASCADE, to='administracion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('departamento', models.CharField(choices=[('web', 'Web'), ('programacion', 'Programación'), ('administracion', 'Administración'), ('ciberseguridad', 'Ciberseguridad'), ('telefonia', 'Telefonía'), ('sistemas', 'Sistemas'), ('taller', 'Taller')], max_length=20)),
                ('foto_perfil', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
