# Generated by Django 5.0.4 on 2024-06-15 15:22

import administracion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto_perfil',
            field=models.FileField(blank=True, default=administracion.models.fotoDefault, null=True, upload_to='administracion/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto_perfil',
            field=models.FileField(blank=True, default=administracion.models.fotoDefault, null=True, upload_to='administracion/'),
        ),
    ]
