# Generated by Django 5.0.6 on 2024-06-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_cliente_dni_alter_cliente_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.empresa'),
        ),
    ]
