# Generated by Django 5.0.4 on 2024-05-20 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_remove_cliente_apellidos_remove_cliente_correo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('departamento', models.CharField(choices=[('web', 'Web'), ('programacion', 'Programación'), ('administracion', 'Administración'), ('ciberseguridad', 'Ciberseguridad'), ('telefonia', 'Telefonía'), ('sistemas', 'Sistemas'), ('taller', 'Taller')], max_length=20)),
                ('foto_perfil', models.BinaryField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
