# Generated by Django 5.0.4 on 2024-06-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_cliente_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
