# Generated by Django 5.0.4 on 2024-06-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_empleado_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
