# Generated by Django 5.0.4 on 2024-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_empleado_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to='media/administracion'),
        ),
    ]
