# Generated by Django 5.0.4 on 2024-06-12 17:51

import administracion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_alter_cliente_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto_perfil',
            field=models.FileField(blank=True, default=administracion.models.fotoDefault, null=True, upload_to='media/administracion'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto_perfil',
            field=models.FileField(blank=True, default=administracion.models.fotoDefault, null=True, upload_to='media/administracion'),
        ),
    ]
