# Generated by Django 5.0.4 on 2024-06-14 06:16

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(max_length=120)),
                ('comienzo', models.TimeField(blank=True, null=True)),
                ('fin', models.TimeField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tiempo', models.TimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(default='empleado no existente', on_delete=django.db.models.deletion.SET_DEFAULT, to='administracion.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('web', 'Web'), ('programacion', 'Programación'), ('administracion', 'Administración'), ('ciberseguridad', 'Ciberseguridad'), ('telefonia', 'Telefonía'), ('sistemas', 'Sistemas'), ('taller', 'Taller')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'Proceso'), ('pausa', 'Pausa'), ('terminada', 'Terminada')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('importante', 'Importante'), ('urgente', 'Urgente')], max_length=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.cliente')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.empleado')),
                ('lines', models.ManyToManyField(blank=True, to='incidencias.line')),
            ],
        ),
    ]
