# Generated by Django 5.0.6 on 2024-06-13 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_cliente_empresa'),
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(max_length=120)),
                ('comienzo', models.TimeField(blank=True, null=True)),
                ('fin', models.TimeField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tiempo', models.TimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(default='empleado no existente', on_delete=django.db.models.deletion.SET_DEFAULT, to='administracion.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='incidencia',
            name='lines',
            field=models.ManyToManyField(blank=True, to='incidencias.line'),
        ),
    ]
