# Generated by Django 5.0.4 on 2024-05-18 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_cliente_user_empleado_user'),
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.empleado'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'Proceso'), ('pausa', 'Pausa'), ('terminada', 'Terminada')], default='pendiente', max_length=20),
        ),
    ]
