# Generated by Django 5.0.4 on 2024-05-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_alter_incidencia_empleado_alter_incidencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('importante', 'Importante'), ('urgente', 'Urgente')], max_length=10, null=True),
        ),
    ]
