# Generated by Django 5.0.4 on 2024-05-28 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_alter_incidencia_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
