# Generated by Django 5.0.4 on 2024-05-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0005_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='lines',
            field=models.ManyToManyField(blank=True, to='incidencias.line'),
        ),
    ]
