# Generated by Django 5.0.4 on 2024-05-30 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0006_incidencia_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
