# Generated by Django 5.0.4 on 2024-05-30 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_cliente_user_empleado_user'),
        ('incidencias', '0007_line_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='empleado',
            field=models.ForeignKey(default='empleado no existente', on_delete=django.db.models.deletion.SET_DEFAULT, to='administracion.empleado'),
        ),
    ]
