# Generated by Django 5.0.4 on 2024-06-14 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especificaciones', models.JSONField(blank=True, null=True)),
                ('precio_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo', models.CharField(choices=[('portatil', 'Portátil'), ('placa', 'Placa'), ('teclado', 'Teclado'), ('raton', 'Ratón'), ('tablet', 'Tablet')], max_length=20)),
                ('destacado', models.BooleanField(default=False, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='inventario/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('direccion', models.TextField()),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'En preparación'), (2, 'Pausa'), (3, 'Preparado'), (4, 'Enviado')])),
                ('subtotal', models.FloatField(null=True)),
                ('IVA', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField()),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.pedido')),
                ('articulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
            ],
        ),
    ]
