# Generated by Django 5.0.4 on 2024-05-19 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='lineas',
        ),
        migrations.AddField(
            model_name='linea',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.pedido'),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('portatil', 'Portátil'), ('placa', 'Placa'), ('teclado', 'Teclado'), ('raton', 'Ratón'), ('tablet', 'Tablet')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='IVA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.BinaryField(blank='True', null=True),
        ),
    ]
