# Generated by Django 5.0.4 on 2024-05-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('portatil', 'Portátil'), ('placa', 'Placa'), ('teclado', 'Teclado'), ('raton', 'Ratón'), ('tablet', 'Tablet')], default='portatil', max_length=20),
        ),
    ]
