# Generated by Django 5.0.4 on 2024-05-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea',
            name='p',
        ),
    ]
