# Generated by Django 5.0.4 on 2024-05-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.BinaryField(null=True),
        ),
    ]
