# Generated by Django 5.0.4 on 2024-05-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_destacado_alter_producto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('portatil', 'Portátil'), ('placa', 'Placa'), ('teclado', 'Teclado'), ('raton', 'Ratón'), ('tablet', 'Tablet')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.BinaryField(),
        ),
    ]
