# Generated by Django 5.0.4 on 2024-06-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_linea_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='especificaciones',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
