# Generated by Django 5.0.4 on 2024-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_especificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
