# Generated by Django 5.0.6 on 2024-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_precio_descuento_producto_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.BinaryField(blank='True', null=True),
        ),
    ]
