# Generated by Django 5.0.6 on 2024-05-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_pedido_lineas_linea_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.FloatField(null=True),
        ),
    ]
