# Generated by Django 5.0.6 on 2024-06-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='mensajeria/'),
        ),
    ]
