# Generated by Django 5.0.6 on 2024-05-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_pedido_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='IVA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
