# Generated by Django 5.0.4 on 2024-05-14 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='mensajes',
        ),
        migrations.AddField(
            model_name='chat',
            name='mensajes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mensajeria.mensaje'),
        ),
    ]
