# Generated by Django 5.0.6 on 2024-05-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fichero',
            field=models.FileField(blank=True, null=True, upload_to='ficheros/'),
        ),
    ]
