# Generated by Django 5.0.6 on 2024-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_mensaje_fichero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fichero',
            field=models.FileField(blank=True, null=True, upload_to='mensajeria/'),
        ),
    ]
