# Generated by Django 5.0.4 on 2024-05-16 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_alter_chat_id_usuariochat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='chat',
            field=models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, to='mensajeria.chat'),
        ),
    ]
